Bump build-validate-publish workflow image
This should fix build issues like the following:

    **Setup toolchain**

    $ pipx --version
      1.8.0
    $ pipx install bikeshed --quiet
      creating virtual environment...
      installing bikeshed...
      done! ✨ 🌟 ✨
        installed package bikeshed 6.1.1, installed using Python 3.10.12
        These apps are now globally available
          - bikeshed
    $ bikeshed update
      Bikeshed now requires Python 3.12 or higher; you are on 3.10.12.
          For instructions on how to set up a pyenv with 3.12, see:
          https://speced.github.io/bikeshed/#installing
    Command `bikeshed update` failed with exit code: 1.
    Error: Process completed with exit code 1.

The `ubuntu-24.04` runner image includes Python 3.12.3.